config/routes.rb
Rails.application.routes.draw do
  resources :password_resets
  root to: "category#index"
  resources :products, only: [:show] do
    resources :my_products, only: [:create, :destroy]
  end
  get 'about' => 'welcome#about'
  resources :my_products_notifications, only: [:create, :destroy]
  resources :category, only: [:index, :show]
  resources :submissions, only: [:new, :create]
  resources :users, only: [:new, :create, :show]
  resources :user_sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :base, only: [:index]
    resources :submissions, only: [:index, :edit, :update, :destroy]
    resources :products
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  serialize :features
  validates_uniqueness_of :sku
  has_many :price_logs
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :my_products


  class << self
    def create_from_sku(sku)
      lookup = ItemLookup.new(sku)
      return unless lookup.items
      item = lookup.items.first
      current_price = item[:current_price] || AmazonScraper.new(item[:detail_page_url]).price
      create(
        features: item[:features],
        sku: item[:sku],
        detail_page_url: item[:detail_page_url],
        review_url: item[:review_url],
        title: item[:title].truncate(254),
        current_price: NumberFormatter.format_price_string(current_price),
        large_image_url: item[:large_image_url],
        medium_image_url: item[:medium_image_url],
        small_image_url: item[:small_image_url],
        brand: item[:brand]
      )
    end

    def create_multiple(sku_array)
      lookup = ItemLookup.new(sku_array)
      if lookup.items
        lookup.items.map do |item|
          begin
            create(item)
          rescue => e

          end
        end
      end
    end


    def percent_discounts(products)
      good_products = products.select {|product|
        product.current_average_price.present? && product.current_average_price > 0
      }
      good_products.sort_by { |product| product.percent_off }.compact.reverse
    end

    def top_products_with_logs(products)
      percent_discounts(products).map do |product|
        [product, product.price_log_hash, product.percent_discount]
      end
    end

    def get_products_for(category)
      return Product.all unless category
      joins(:categories).where('categories.name = ?', category)
    end

    def category_discounts(category = nil, days = 30, items = 100)
      products = get_products_for(category).includes(:price_logs).references(:price_logs).where("price_logs.created_at >= ? ", days.days.ago).limit(items)
      top_products_with_logs(products)
    end

    def update_urls
      all.each do |product|
        product.update(
          detail_page_url: PostRank::URI.clean(product.detail_page_url),
          review_url: PostRank::URI.clean(product.review_url)
        )
      end
    end

    def update_asin_tag(old_asin)
      all.each do |product|
        product.update(
                 detail_page_url: product.detail_page_url.gsub(old_asin, ENV['ASIN_TAG']),
                 review_url: product.review_url.gsub(old_asin, ENV['ASIN_TAG'])
        )
      end
    end
  end

  def percent_off
    NumberConverter.percent_off(self.current_average_price.to_i, self.current_price)
  end

  def percent_discount(days = 30)
    if get_price_logs(days).length > 0
      NumberConverter.percent_off(current_average_price.to_i, current_price)
    else
      0
    end
  end

  def average_price(days = 30)
    price_logs = get_price_logs(days)
    return 0 if price_logs.length == 0
    sum = price_logs.reduce(0) { |memo, price| memo + price.price.to_i }
    sum / price_logs.length
  end

  def update_from_sku
    self.update(ItemLookup.new(self.sku).items.first)
  end

  def get_price_logs(days = 30)
    price_logs.sort_by { |log| log.created_at }.select do |log|
      log.created_at >= days.day.ago
    end
  end

  def price_log_hash(days = 30)
    get_price_logs(days).reduce({}) do |logs_hash, log|
      logs_hash[log.date_string] = log.in_dollars
      logs_hash
    end
  end

  def add_categories(category_array)
    category_array.each do |category|
      category = category.split(' ').map(&:capitalize).join(' ')

      unless Category.find_by(name: category)
        Category.create(name: category)
      end

      category_in_db = Category.find_by(name: category)

      unless categories.include?(category_in_db)
        ProductCategory.create(product_id: self.id, category_id: category_in_db.id)
      end
    end
  end

  def update_categories(category_array)
    self.product_categories.destroy_all
    self.add_categories(category_array)
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :get_product_and_categories, only: [:edit, :update, :destroy]

    def index
      @products = Product.all
    end

    def new
    end

    def create
      if new_params_set?
        sku = params[:sku]
        categories = SubmissionHelper.split_categories(params[:category])
        ProductAdder.add_category([sku], categories)
        flash[:notice] = "Product successfully added"
        redirect_to admin_products_path
      else
        flash[:notice] = "Please set params"
        redirect_to :back
      end
    end

    def edit
      if @product.categories.count > 0
        @selection = @product.categories.first.id
      else
        @selection = 0
      end
    end

    def update
      category = Category.find(params[:category])
      ProductCategory.find_or_create_by(product: @product, category: category)
      redirect_to edit_admin_product_path(@product)
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path
    end

    private
    def get_product_and_categories
      @product = Product.find(params[:id])
      @categories = ProductCategory.where(product_id: @product.id).includes(:category)
    end

    def new_params_set?
      !(params[:sku].strip.blank? || params[:category].strip.blank?)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show]

  def show
    meta_tag_setter(
      "#{@product.title}",
      'Best discounts for health and beauty products',
      "#{@product.title}," + key_words,
      true
    )
    @chart_hash = @product.price_log_hash
  end


  private
  def get_product
    @product = Product.find(params[:id])
  end
end

app/views/admin/products/edit.html.erb
<%= link_to(@product.title, @product) %>

<%= form_tag(admin_product_path(@product), method: :patch) do %>
  <%= select_tag(:category, options_from_collection_for_select(Category.all, 'id', 'name', @selection), prompt: "Select something") %>
  <%= submit_tag 'Update' %>
<% end -%>

app/views/admin/products/index.html.erb
<ul>
  <%= link_to 'Add New Product', new_admin_product_path %>
  <% @products.each do |product| %>
    <li id="<%= product.sku %>">
      <%= product.title %>
      <%= link_to 'Edit', edit_admin_product_path(product) %>
      <%= link_to 'Delete', admin_product_path(product), method: :delete %>
    </li>
  <% end %>
</ul>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="loginbox mainbox col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
    <div class="panel panel-info">
      <div class="panel-heading">
        <div class="panel-title">Add a Product</div>
      </div>
      <div class="panel-body login-panel">
        <% if flash[:notice] %>
          <div class="login-alert alert alert-success col-sm-12">
            <%= flash[:notice] %>
          </div>
        <% end %>
        <%= form_tag({:action => :create}, {:method => :post}) do%>
        <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-qrcode"></i></span>
            <%= text_field_tag :sku, nil,  placeholder: 'Enter SKU from Amazon', class: 'form-control' %>
          </div>

          <div class="input-group">
            <span class="input-group-addon"><i class="glyphicon glyphicon-tag"></i></span>
            <%= text_field_tag :category, nil,  placeholder: 'Enter Category', class: 'form-control' %>
          </div>

          <div class="form-group">
            <div class="col-sm-12 controls">
              <%= submit_tag 'Add Product', class: "btn btn-success pull-right" %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>