config/routes.rb
Rails.application.routes.draw do
  resources :password_resets
  root to: "category#index"
  resources :products, only: [:show] do
    resources :my_products, only: [:create, :destroy]
  end
  get 'about' => 'welcome#about'
  resources :my_products_notifications, only: [:create, :destroy]
  resources :category, only: [:index, :show]
  resources :submissions, only: [:new, :create]
  resources :users, only: [:new, :create, :show]
  resources :user_sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :base, only: [:index]
    resources :submissions, only: [:index, :edit, :update, :destroy]
    resources :products
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  serialize :features
  validates_uniqueness_of :sku
  has_many :price_logs
  has_many :product_categories
  has_many :categories, through: :product_categories
  has_many :my_products


  class << self
    def create_from_sku(sku)
      lookup = ItemLookup.new(sku)
      return unless lookup.items
      item = lookup.items.first
      current_price = item[:current_price] || AmazonScraper.new(item[:detail_page_url]).price
      create(
        features: item[:features],
        sku: item[:sku],
        detail_page_url: item[:detail_page_url],
        review_url: item[:review_url],
        title: item[:title].truncate(254),
        current_price: NumberFormatter.format_price_string(current_price),
        large_image_url: item[:large_image_url],
        medium_image_url: item[:medium_image_url],
        small_image_url: item[:small_image_url],
        brand: item[:brand]
      )
    end

    def create_multiple(sku_array)
      lookup = ItemLookup.new(sku_array)
      if lookup.items
        lookup.items.map do |item|
          begin
            create(item)
          rescue => e

          end
        end
      end
    end


    def percent_discounts(products)
      good_products = products.select {|product|
        product.current_average_price.present? && product.current_average_price > 0
      }
      good_products.sort_by { |product| product.percent_off }.compact.reverse
    end

    def top_products_with_logs(products)
      percent_discounts(products).map do |product|
        [product, product.price_log_hash, product.percent_discount]
      end
    end

    def get_products_for(category)
      return Product.all unless category
      joins(:categories).where('categories.name = ?', category)
    end

    def category_discounts(category = nil, days = 30, items = 100)
      products = get_products_for(category).includes(:price_logs).references(:price_logs).where("price_logs.created_at >= ? ", days.days.ago).limit(items)
      top_products_with_logs(products)
    end

    def update_urls
      all.each do |product|
        product.update(
          detail_page_url: PostRank::URI.clean(product.detail_page_url),
          review_url: PostRank::URI.clean(product.review_url)
        )
      end
    end

    def update_asin_tag(old_asin)
      all.each do |product|
        product.update(
                 detail_page_url: product.detail_page_url.gsub(old_asin, ENV['ASIN_TAG']),
                 review_url: product.review_url.gsub(old_asin, ENV['ASIN_TAG'])
        )
      end
    end
  end

  def percent_off
    NumberConverter.percent_off(self.current_average_price.to_i, self.current_price)
  end

  def percent_discount(days = 30)
    if get_price_logs(days).length > 0
      NumberConverter.percent_off(current_average_price.to_i, current_price)
    else
      0
    end
  end

  def average_price(days = 30)
    price_logs = get_price_logs(days)
    return 0 if price_logs.length == 0
    sum = price_logs.reduce(0) { |memo, price| memo + price.price.to_i }
    sum / price_logs.length
  end

  def update_from_sku
    self.update(ItemLookup.new(self.sku).items.first)
  end

  def get_price_logs(days = 30)
    price_logs.sort_by { |log| log.created_at }.select do |log|
      log.created_at >= days.day.ago
    end
  end

  def price_log_hash(days = 30)
    get_price_logs(days).reduce({}) do |logs_hash, log|
      logs_hash[log.date_string] = log.in_dollars
      logs_hash
    end
  end

  def add_categories(category_array)
    category_array.each do |category|
      category = category.split(' ').map(&:capitalize).join(' ')

      unless Category.find_by(name: category)
        Category.create(name: category)
      end

      category_in_db = Category.find_by(name: category)

      unless categories.include?(category_in_db)
        ProductCategory.create(product_id: self.id, category_id: category_in_db.id)
      end
    end
  end

  def update_categories(category_array)
    self.product_categories.destroy_all
    self.add_categories(category_array)
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < BaseController
    before_action :get_product_and_categories, only: [:edit, :update, :destroy]

    def index
      @products = Product.all
    end

    def new
    end

    def create
      if new_params_set?
        sku = params[:sku]
        categories = SubmissionHelper.split_categories(params[:category])
        ProductAdder.add_category([sku], categories)
        flash[:notice] = "Product successfully added"
        redirect_to admin_products_path
      else
        flash[:notice] = "Please set params"
        redirect_to :back
      end
    end

    def edit
      if @product.categories.count > 0
        @selection = @product.categories.first.id
      else
        @selection = 0
      end
    end

    def update
      category = Category.find(params[:category])
      ProductCategory.find_or_create_by(product: @product, category: category)
      redirect_to edit_admin_product_path(@product)
    end

    def destroy
      @product.destroy
      redirect_to admin_products_path
    end

    private
    def get_product_and_categories
      @product = Product.find(params[:id])
      @categories = ProductCategory.where(product_id: @product.id).includes(:category)
    end

    def new_params_set?
      !(params[:sku].strip.blank? || params[:category].strip.blank?)
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:show]

  def show
    meta_tag_setter(
      "#{@product.title}",
      'Best discounts for health and beauty products',
      "#{@product.title}," + key_words,
      true
    )
    @chart_hash = @product.price_log_hash
  end


  private
  def get_product
    @product = Product.find(params[:id])
  end
end

app/views/products/_product_show_card.html.erb
<% cache(@product) do %>
  <div class="col-xs-10 col-xs-offset-1">
    <div class="profile">
      <div class="col-xs-12 product-show-container">
        <div class="col-xs-12 categories-header">
          <h2>Categories:
            <% @product.categories.each do |category| %>
              <span class="label label-info"><%= link_to category.name, category_path(category.name) %></span>
            <% end %>
          </h2>
        </div>
        <div class="col-xs-6 text-center">
          <figure>
            <img src="<%= @product.large_image_url %>" alt="" class="img-responsive">
          </figure>
        </div>
        <div class="col-xs-6 ">
          <div class="title-description">
            <h2><%= @product.title %></h2>
            <% if logged_in? && current_user.tracked?(@product) %>
            <% else %>
              <%= link_to product_my_products_path(@product), method: :post, class: 'btn btn-success pull-right track-it ' do %>
                Track-it <span class="glyphicon glyphicon-ok-circle"> </span>
              <% end %>
            <% end %>
            <p><strong>Average price: </strong><%= ProductCurrency.format_money(@product.average_price) %></p>

            <p><strong>Current price: </strong><%= ProductCurrency.format_money(@product.current_price) %></p>

            <p>
              <strong>Percent discount: </strong>
              <% if @product.percent_discount > 0 %>
                <% percent_style = 'text-success' %>
              <% elsif @product.percent_discount < 0 %>
                <% percent_style = 'text-danger' %>
              <% end %>
              <span class="<%= percent_style %>"><%= NumberFormatter.format_percentage(@product.percent_discount).first %></span>
            </p><br/>
          </div>
          <% if @product.features %>
            <p><strong>Features: </strong><br/></p>
            <ul>
              <% @product.features.each do |feature| %>
                <li><%= feature %></li>
              <% end %>
            </ul>
          <% end %>
          <div class="text-center">
            <p>
              <%= link_to @product.detail_page_url, class: 'btn buy-now-large ', target: '_blank' do %>
                <span class="glyphicon glyphicon-shopping-cart"></span> Buy now!
              <% end %>
              <%= link_to @product.review_url, class: 'btn reviews', target: '_blank' do %>
                Read Reviews <span class="glyphicon glyphicon-list-alt"></span>
              <% end %>

            </p>
          </div>
        </div>
      </div>
      <div class="col-xs-8 col-sm-10 col-md-12 divider text-center">
        <%= line_chart(@chart_hash,
                       {
                         discrete: true,
                         library:
                           {
                             hAxis:
                               {
                                 slantedText: true, slantedTextAngle: 40
                               },
                             vAxis:
                               {
                                 format: '$#,###'
                               }
                           }
                       }) %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
<% end %>

app/views/products/show.html.erb
<div class="container-fluid cards-wrapper" style="background-color:#e8e8e8">
  <div class="container container-pad" id="property-lngs">
    <%= render 'product_show_card' %>
  </div>
</div>