config/routes.rb
Rails.application.routes.draw do
  resources :password_resets
  root to: "category#index"
  resources :products, only: [:show] do
    resources :my_products, only: [:create, :destroy]
  end
  get 'about' => 'welcome#about'
  resources :my_products_notifications, only: [:create, :destroy]
  resources :category, only: [:index, :show]
  resources :submissions, only: [:new, :create]
  resources :users, only: [:new, :create, :show]
  resources :user_sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :base, only: [:index]
    resources :submissions, only: [:index, :edit, :update, :destroy]
    resources :products
  end
end

app/models/submission.rb
class Submission < ActiveRecord::Base
  validates :category, presence: true
  validates :sku, presence: true
  validates :sku, length: { is: 10, message: "Invalid SKU" }
  has_many :categories
end

app/models/submission_helper.rb
class SubmissionHelper
  class << self
    def split_categories(category_string)
      category_string.split(",").map(&:strip)
    end
  end
end

app/controllers/admin/submissions_controller.rb
module Admin
  class SubmissionsController < BaseController
    before_action :find_submission, only: [:edit, :destroy]
    def index
      @submissions = Submission.all
    end

    def edit
      @amazon_detail_page = "http://www.amazon.com/gp/product/#{@submission.sku}/"
    end

    def update
      categories = SubmissionHelper.split_categories(params[:submission][:category])
      sku = params[:submission][:sku]
      Product.create_multiple([sku])
      ProductAdder.add_category([sku], categories)
      submission = Submission.find_by(sku: sku)
      submission.destroy
      redirect_to admin_submissions_path
    end

    def destroy
      @submission.destroy
      redirect_to admin_submissions_path
    end

    private
    def find_submission
      @submission = Submission.find(params[:id])
    end
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def new
    meta_tag_setter(
      "Suggest product",
      'Best discounts for health and beauty products',
      key_words,
      false
    )
    @submission = Submission.new
  end

  def create
    @submission = Submission.new(allowed_params)
    if @submission.save
      flash[:success] = "Thank you for your submission, it will be reviewed shortly"
      redirect_to new_submission_path
    else
      render :new
    end
  end

  private
  def allowed_params
    params.require(:submission).permit(:sku, :category)
  end
end

app/views/admin/submissions/edit.html.erb
<%= form_for([:admin, @submission]) do |f| %>
  <%= f.text_field :sku %>
  <%= f.text_field :category %>
  <%= f.submit 'Add' %>
<% end %>

<%= link_to 'Amazon detail page', @amazon_detail_page, id: 'amazon-link' %>

app/views/admin/submissions/index.html.erb
<% @submissions.each do |submission| %>
  <h3>Submissions</h3>
  SKU: <%= submission.sku %>
  Category: <%= submission.category %>
  <%= link_to 'Add', edit_admin_submission_path(submission), class: 'btn btn-success '  %>
  <%= link_to 'Reject', admin_submission_path(submission), method: :delete, class: 'btn btn-danger ' %></br>
  <%= link_to 'Amazon detail page', "http://www.amazon.com/gp/product/#{submission.sku}/" %>
<% end %>