config/routes.rb
Rails.application.routes.draw do
  resources :password_resets
  root to: "category#index"
  resources :products, only: [:show] do
    resources :my_products, only: [:create, :destroy]
  end
  get 'about' => 'welcome#about'
  resources :my_products_notifications, only: [:create, :destroy]
  resources :category, only: [:index, :show]
  resources :submissions, only: [:new, :create]
  resources :users, only: [:new, :create, :show]
  resources :user_sessions, only: [:new, :create, :destroy]
  namespace :admin do
    resources :base, only: [:index]
    resources :submissions, only: [:index, :edit, :update, :destroy]
    resources :products
  end
end

app/views/layouts/_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53102809-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_footer.html.erb
<div class="panel-footer col-xs-12"> Mass Metrics © </div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <%= link_to 'MassMetrics--', root_path, class: "navbar-brand", id: 'logo' %>
  </div>
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Browse', category_index_path %></li>
      <li><%= link_to 'Suggest a product', new_submission_path %></li>
      <li><%= link_to 'About', about_path %></li>
      <% if logged_in? %>
        <li><%= link_to 'My Products', current_user %></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav pull-right">
      <% if logged_in? %>
        <li><%= link_to current_user.email, '#', class: 'user-email' %></li>
        <li><%= link_to 'Logout', user_session_path(current_user.id), method: :delete %></li>
        <% if current_user.role?(:admin) %>
          <li>
            <% if new_submissions > 0 %>
              <%= link_to "Admin (#{new_submissions})", admin_base_index_path %>
            <% else %>
              <%= link_to 'Admin', admin_base_index_path %>
            <% end %>
          </li>
        <% end %>
      <% else %>
        <li><%= link_to 'Register', new_user_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>
    </ul>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= display_meta_tags :site => 'Mass Metrics' %>
</head>
<body>
<div class="container">
  <%= render partial: "layouts/nav" %>
  <% if flash[:notice] %>
    <div class="alert alert-danger">
      <p class="text-center"><%= flash[:notice] %></p>
    </div>
  <% end %>
  <%= yield %>
  <%= render partial: "layouts/footer" %>
</div>

<%= render 'layouts/analytics' %>
</body>
</html>